config/routes.rb
Rails.application.routes.draw do

  devise_for :interns

  root 'static_pages#index'
  get 'admin' => 'static_pages#admin'
  resources :interns
  resources :companies do
    collection do
      get 'map' => 'companies#company_map'
    end
  end
  resources :employees

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def admin
    @interns = Intern.all
    @employees = Employee.all
    @companies = Company.all.sort_by { |company| company.name }
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<% provide(:title, "Admin Area") %>
<% provide(:subtitle, "Proceed With Caution") %>
<div id="top">
  <h2>Super cool things you can do as an admin:</h2>
  <ul id="menu">
    <li><%= link_to "Create Companies", new_company_path %></li>
    <li><%= link_to "Create Interns", new_intern_path %></li>
    <li><%= link_to "Create Employees", new_employee_path %></li>
    <li><%= link_to "Edit or Delete Companies", "#companies" %></li>
    <li><%= link_to "Edit or Delete Interns", "#interns" %></li>
    <li><%= link_to "Edit or Delete Employees", "#employees" %></li>
  </ul>
</div>

<div class="row" id="companies">
  <div class="col-md-6 col-md-offset-3">
    <h2>Edit or Delete Companies</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <td>Company Name</td>
          <td></td>
          <td></td>
        </tr>
      </thead>
      <% @companies.each do |company| %>
        <tr>
          <td><%= company.name %></td>
          <td><%= button_to "Edit", edit_company_path(company), method: :get %></td>
          <td><%= button_to "Delete", company_path(company), method: :delete, data: { confirm: "Are you sure you want to delete #{company.name}?" } %></td>
        </tr>
      <% end %>
    </table>
    <%= link_to "Back to Top", "#top" %>
  </div>
</div>

<div class="row" id="interns">
  <div class="col-md-6 col-md-offset-3">
    <h2>Edit or Delete Interns</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <td>Intern Name</td>
          <td></td>
          <td></td>
        </tr>
      </thead>
      <% @interns.each do |intern| %>
        <tr>
          <td><%= intern.name %></td>
          <td><%= button_to "Edit", edit_intern_path(intern), method: :get %></td>
          <td><%= button_to "Delete", intern_path(intern), method: :delete, data: { confirm: "Are you sure you want to delete #{intern.name}?" } %></td>
        </tr>
      <% end %>
    </table>
    <%= link_to "Back to Top", "#top" %>
  </div>
</div>

<div class="row" id="employees">
  <div class="col-md-6 col-md-offset-3">
    <h2>Edit or Delete Employees</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <td>Employee Name</td>
          <td></td>
          <td></td>
        </tr>
      </thead>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= button_to "Edit", edit_employee_path(employee), method: :get %></td>
          <td><%= button_to "Delete", employee_path(employee), method: :delete, data: { confirm: "Are you sure you want to delete #{employee.name}?" } %></td>
        </tr>
      <% end %>
    </table>
    <%= link_to "Back to Top", "#top" %>
  </div>
</div>

<script>
  var scrollFunction = function(){
    var menuId = $(this).attr("href");
    $("body").animate({scrollTop: $(menuId).offset().top - 50}, "slow");
    return false;
  }
  $("#menu a").click(scrollFunction);
  $("#top a").click(scrollFunction);

</script>

app/views/static_pages/index.html.erb
<% provide(:title, "Ada Internships") %>