config/routes.rb
Rails.application.routes.draw do

  devise_for :interns

  root 'static_pages#index'
  get 'admin' => 'static_pages#admin'
  resources :interns
  resources :companies do
    collection do
      get 'map' => 'companies#company_map'
    end
  end
  resources :employees

end

app/models/company.rb
require 'open-uri'

class Company < ActiveRecord::Base
  has_many :interns
  has_many :employees, dependent: :destroy
  validates :name, presence: true


  # define ActiveRecord scopes for
  # :sorted_by, :search_query, :with_cohort_id
  filterrific(
  default_filter_params: { sorted_by: 'name_asc' },
  available_filters: [
    :sorted_by,
    :search_query,
    ]
  )

  scope :search_query, lambda { |query|
    return nil  if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conditions = 2
    where(
      terms.map {
        or_clauses = [
          "LOWER(companies.name) LIKE ?",
          "LOWER(companies.website) LIKE ?"
        ].join(' OR ')
        "(#{ or_clauses })"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conditions }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^name_/
      order("LOWER(companies.name) #{ direction }")
    when /^num_interns_/
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  delegate :name, :to => :company, :prefix => true

  def self.options_for_sorted_by
      [
        ['Name (a-z)', 'name_asc'],
        ['Name (z-a)', 'name_desc'],
        ['# of Interns (descending)', 'num_interns_desc'],
      ]
  end



  # returns the number of interns, including those for cohort 4
  def num_interns
    prev_interns = self.interns.count
    self.sponsor_four.nil? ? (prev_interns) : (prev_interns + self.sponsor_four)
  end

  # returns an array of which cohorts the company has sponsored
  def which_cohorts
    cohorts = []
    self.interns.each do |intern|
      cohorts.push(intern.cohort)
    end
    cohorts.push(4) if !self.sponsor_four.nil?
    return cohorts.uniq
  end

  # returns a hash of results of a query of the company's Glassdoor info
  def getGlassdoor
    response = open("http://api.glassdoor.com/api/api.htm?t.p=49111&t.k=kHImtMBuowe&userip=0.0.0.0&useragent=&format=json&v=1&action=employers&q=#{self.name}&city=Seattle").read
    parsed_json = ActiveSupport::JSON.decode(response)
    results = parsed_json["response"]
    return results
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :get_company, only: [:show, :destroy, :edit, :update]

  def index
    @filterrific = initialize_filterrific(
    Company,
    params[:filterrific],
      :select_options => {
        sorted_by: Company.options_for_sorted_by,
      }
    ) or return
    @companies = @filterrific.find
    if @filterrific.sorted_by == "num_interns_desc"
      @companies = @companies.sort_by{ |company| company.num_interns }.reverse
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    results = @company.getGlassdoor
    @ratings = results["employers"].first
    @url = results["attributionURL"]
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def update
    @company.update(company_params[:company])
    redirect_to admin_path
  end

  def create
    Company.create(company_params[:company])
    redirect_to admin_path
  end

  def destroy
    @company.destroy
    redirect_to admin_path
  end

  def company_map
    @companies = Company.all
    @hash = Gmaps4rails.build_markers(@companies) do |company, marker|
      marker.lat company.latitude
      marker.lng company.longitude
      marker.infowindow company.name
      # marker.name company.name
      # marker.infowindow "I'm a company"
    end
  end

  private
    def get_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.permit(company:[:id, :name, :street, :city, :state, :zip, :website, :logo])
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => {:class => "form-group"} do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', :required => true %>
    <%= f.label :street %>
    <%= f.text_field :street, class: 'form-control' %>
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>
    <%= f.label :zip %>
    <%= f.text_field :zip, class: 'form-control' %>
    <%= f.label :website %>
    <%= f.text_field :website, class: 'form-control' %>
    <%= f.label :logo %>
    <%= f.file_field :logo %>
    <br>
    <%= f.submit value: "#{button_text}", class: "btn btn-primary"%>
  </fieldset>
<% end %>

app/views/companies/_list.html.erb
<div id="filterrific_results">
  <% count = 0 %>
  <% companies.each do |company| %>
    <% if count % 3 == 0 %>
      <div class="row">
    <% end %>
      <div class="col-sm-4 portfolio-item">
          <a href= <%= company.website %> >
            <%= image_tag("logo/#{company.logo}", alt: "#{company.name} logo", class: "img-responsive center-block") %>
          </a>
          <h3>
            <%= link_to company.name, company_path(company.id) %>
          </h3>
          <h4><strong>Number of Interns: </strong><%= company.num_interns %></h4>
          <h4><strong><%= "Cohort".pluralize(company.which_cohorts.length) %> Sponsored: </strong><%= company.which_cohorts.join(", ") %></h4>
      </div>
    <% count += 1 %>
    <% if count % 3 == 0 %>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>

app/views/companies/company_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div class="row">
  <div class="col-md-9" id="sidebar_builder" style='height: 400px;'>
  </div>
  <div class="col-md-3" id='sidebar_container'>
  </div>
</div>

<script type="text/javascript">
function createSidebarLi(json){
return ("<li><a>" + json.name + "</a></li>");
};

function bindLiToMarker($li, marker){
$li.on('click', function(){
  // handler.getMap().setZoom(14);
  marker.setMap(handler.getMap()); //because clusterer removes map property from marker
  marker.panTo();
  google.maps.event.trigger(marker.getServiceObject(), 'click');
})
};

function createSidebar(json_array){
_.each(json_array, function(json){
  console.log(json)
  var $li = $( createSidebarLi(json.infowindow) );
  $li.appendTo('#sidebar_container');
  bindLiToMarker($li, json.marker);
});
};

handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'sidebar_builder'}}, function(){
// var json_array = [
//   { lat: 40, lng: -80, name: 'Foo', infowindow: "I'm Foo" },
//   { lat: 45, lng: -90, name: 'Bar', infowindow: "I'm Bar" },
//   { lat: 50, lng: -85, name: 'Baz', infowindow: "I'm Baz" }
// ];

var json_array = <%=raw @hash.to_json %>

var markers = handler.addMarkers(json_array);

_.each(json_array, function(json, index){
  json.marker = markers[index];
});

createSidebar(json_array);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
});
</script>

app/views/companies/edit.html.erb
<% provide(:title, "Edit Company Information") %>
<%= render partial: 'form', locals: {method_type: :patch, button_text: "Edit Company"} %>

app/views/companies/index.html.erb
<% provide(:title, "Sponsoring Companies") %>
<%= link_to "View on a Map", map_companies_path %>

<%#
  Filterrific adds the `form_for_filterrific` view helper:
  * adds dom id 'filterrific_filter'
  * applies javascript behaviors:
      * AJAX form submission on change
      * AJAX spinner while AJAX request is being processed
  * sets form_for options like :url, :method and input name prefix
%>
<%= form_for_filterrific @filterrific do |f| %>
  <div>
    Search
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>
  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>

<%= render(
  partial: 'companies/list',
  locals: { companies: @companies }
) %>

app/views/companies/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'companies/list',
    :locals => { :companies => @companies }
  )
) %>
$("#filterrific_results").html("<%= js %>");

app/views/companies/new.html.erb
<% provide(:title, "Add a Company") %>
<%= render partial: 'form', locals: {button_text: "Create Company"} %>

app/views/companies/show.html.erb
<% provide(:title, @company.name) %>

<% provide(:subtitle, @company.street) %>
<div class="row">
    <!-- Intern section -->
    <% interns = @company.interns %>
    <div class="col-lg-3 col-sm-4">
      <h2><%= "Intern".pluralize(@company.num_interns) %></h2>
        <% interns.each do |intern| %>
          <p><%= link_to intern.name, intern_path(intern) %>, Cohort <%= intern.cohort %></p>
        <% end %>
        <% if @company.sponsor_four %>
          <p><%= @company.name %> will sponsor <%= @company.sponsor_four %> <%= "internship".pluralize(@company.sponsor_four) %> in Cohort 4</p>
        <% end %>
    </div>
    <!-- End intern section -->

    <!-- Employee section -->
    <% num_emp = @company.employees.count %>
    <% if num_emp != 0 %>
      <div class="col-lg-3 col-sm-4">
        <h2><%= "Contact".pluralize(num_emp) %></h2>
        <% @company.employees.each do |employee| %>
          <h4><%= link_to employee.name, employee_path(employee) %></h4>
          <p><%= employee.position %></p>
        <% end %>
      </div>
    <% end %>
    <!-- End employee section -->

    <!-- Glassdoor section -->
      <div class="col-lg-3 col-sm-4">
        <h2>Glassdoor Stats</h2>
        <% if @ratings %>
          <p>Overall rating: <%= @ratings["overallRating"] %> <%= @ratings["ratingDescription"]%></p>
          <p>Compensation and Benefits rating: <%= @ratings["compensationAndBenefitsRating"]%></p>
          <p>Career Opportunities Rating: <%= @ratings["careerOpportunitiesRating"] %></p>
          <p>Work Life Balance Rating: <%= @ratings["workLifeBalanceRating"] %></p>
          <p><%= link_to "View on Glassdoor", @url %></p>
        <% else %>
          <p>There are no statistics available for this company on Glassdoor.</p>
        <% end %>
        <a href='https://www.glassdoor.com/index.htm'>powered by <img src='https://www.glassdoor.com/static/img/api/glassdoor_logo_80.png' title='Job Search' /></a>
      </div>
      <!-- End Glassdoor section -->
      <!-- Map section -->
      <div class="col-lg-5 col-sm-12">
        <h2>Location</h2>
        <% url = "https://www.google.com/maps/embed/v1/place?q=" + @company.name.split(" ").join("%20") + "%20Seattle&key=AIzaSyD4Maj1DKSKP4zkhWEygSNOltVsqv3ii4s"%>
        <iframe width="400" height="400" frameborder="0" style="border:0" src=<%= url %> allowfullscreen></iframe>
      </div>
      <!-- End map section -->
</div>