config/routes.rb
Rails.application.routes.draw do

  devise_for :interns

  root 'static_pages#index'
  get 'admin' => 'static_pages#admin'
  resources :interns
  resources :companies do
    collection do
      get 'map' => 'companies#company_map'
    end
  end
  resources :employees

end

app/views/layouts/_footer.html.erb
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p class="text-center">Copyright &copy; <%= link_to "Jennie Buechner", "https://www.linkedin.com/in/jenniebuechner" %> <%= Time.now.year %></p>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Page Header -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%= yield(:title) %> <small><%= yield(:subtitle) %></small></h1>
    </div>
</div>
<!-- /.row -->

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path%>>Home</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Interns", interns_path %>
        </li>
        <li>
          <%= link_to "Companies", companies_path %>
        </li>
        <% if intern_signed_in? %>
              <li><%= link_to "Profile", intern_path(current_intern) %></li>
              <li><%= link_to "Edit Your Profile", edit_intern_path(current_intern) %></li>
              <li><%= link_to "Change your password", edit_intern_registration_path %></li>
              <li><%= link_to "Log out", destroy_intern_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", new_intern_session_path %></li>
            <% end %>
          </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ada Intern Info</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>